// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: ipc/grpc/reswire/resources.proto

package reswire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventLevel int32

const (
	EventLevel_Error EventLevel = 0
	EventLevel_Info  EventLevel = 1
	EventLevel_All   EventLevel = 2
)

// Enum value maps for EventLevel.
var (
	EventLevel_name = map[int32]string{
		0: "Error",
		1: "Info",
		2: "All",
	}
	EventLevel_value = map[string]int32{
		"Error": 0,
		"Info":  1,
		"All":   2,
	}
)

func (x EventLevel) Enum() *EventLevel {
	p := new(EventLevel)
	*p = x
	return p
}

func (x EventLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_grpc_reswire_resources_proto_enumTypes[0].Descriptor()
}

func (EventLevel) Type() protoreflect.EnumType {
	return &file_ipc_grpc_reswire_resources_proto_enumTypes[0]
}

func (x EventLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventLevel.Descriptor instead.
func (EventLevel) EnumDescriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{0}
}

type WatcherEventOut_Op int32

const (
	WatcherEventOut_Created       WatcherEventOut_Op = 0
	WatcherEventOut_Updated       WatcherEventOut_Op = 1
	WatcherEventOut_UpdatedStatus WatcherEventOut_Op = 2
	WatcherEventOut_Deleted       WatcherEventOut_Op = 3
)

// Enum value maps for WatcherEventOut_Op.
var (
	WatcherEventOut_Op_name = map[int32]string{
		0: "Created",
		1: "Updated",
		2: "UpdatedStatus",
		3: "Deleted",
	}
	WatcherEventOut_Op_value = map[string]int32{
		"Created":       0,
		"Updated":       1,
		"UpdatedStatus": 2,
		"Deleted":       3,
	}
)

func (x WatcherEventOut_Op) Enum() *WatcherEventOut_Op {
	p := new(WatcherEventOut_Op)
	*p = x
	return p
}

func (x WatcherEventOut_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatcherEventOut_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_grpc_reswire_resources_proto_enumTypes[1].Descriptor()
}

func (WatcherEventOut_Op) Type() protoreflect.EnumType {
	return &file_ipc_grpc_reswire_resources_proto_enumTypes[1]
}

func (x WatcherEventOut_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatcherEventOut_Op.Descriptor instead.
func (WatcherEventOut_Op) EnumDescriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{12, 0}
}

type CreateResourceIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *Meta  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Spec   []byte `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *CreateResourceIn) Reset() {
	*x = CreateResourceIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceIn) ProtoMessage() {}

func (x *CreateResourceIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceIn.ProtoReflect.Descriptor instead.
func (*CreateResourceIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{0}
}

func (x *CreateResourceIn) GetTarget() *Meta {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CreateResourceIn) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateResourceOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateResourceOut) Reset() {
	*x = CreateResourceOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceOut) ProtoMessage() {}

func (x *CreateResourceOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceOut.ProtoReflect.Descriptor instead.
func (*CreateResourceOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{1}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	When  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`
	Level EventLevel             `protobuf:"varint,2,opt,name=level,proto3,enum=wire.EventLevel" json:"level,omitempty"`
	// todo: would prefer not to render these within the daemon...but don't have a better way right now to send out the args
	Rendered string `protobuf:"bytes,3,opt,name=rendered,proto3" json:"rendered,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *Event) GetLevel() EventLevel {
	if x != nil {
		return x.Level
	}
	return EventLevel_Error
}

func (x *Event) GetRendered() string {
	if x != nil {
		return x.Rendered
	}
	return ""
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind *Type  `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{3}
}

func (x *Meta) GetKind() *Type {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Meta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{4}
}

func (x *Type) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Type) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *Meta `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *GetIn) Reset() {
	*x = GetIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIn) ProtoMessage() {}

func (x *GetIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIn.ProtoReflect.Descriptor instead.
func (*GetIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{5}
}

func (x *GetIn) GetTarget() *Meta {
	if x != nil {
		return x.Target
	}
	return nil
}

type GetOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Spec   []byte `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *GetOut) Reset() {
	*x = GetOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOut) ProtoMessage() {}

func (x *GetOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOut.ProtoReflect.Descriptor instead.
func (*GetOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{6}
}

func (x *GetOut) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetOut) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GetStatusIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *Meta `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *GetStatusIn) Reset() {
	*x = GetStatusIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusIn) ProtoMessage() {}

func (x *GetStatusIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusIn.ProtoReflect.Descriptor instead.
func (*GetStatusIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusIn) GetTarget() *Meta {
	if x != nil {
		return x.Target
	}
	return nil
}

type GetStatusOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Status []byte `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetStatusOut) Reset() {
	*x = GetStatusOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusOut) ProtoMessage() {}

func (x *GetStatusOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusOut.ProtoReflect.Descriptor instead.
func (*GetStatusOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatusOut) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetStatusOut) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateStatusIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *Meta  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Status []byte `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateStatusIn) Reset() {
	*x = UpdateStatusIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusIn) ProtoMessage() {}

func (x *UpdateStatusIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusIn.ProtoReflect.Descriptor instead.
func (*UpdateStatusIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStatusIn) GetTarget() *Meta {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *UpdateStatusIn) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateStatusOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *UpdateStatusOut) Reset() {
	*x = UpdateStatusOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusOut) ProtoMessage() {}

func (x *UpdateStatusOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusOut.ProtoReflect.Descriptor instead.
func (*UpdateStatusOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStatusOut) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// WatcherEventIn is a client request to the service to modify a watcher
type WatcherEventIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag        uint64 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	OnType     *Type  `protobuf:"bytes,2,opt,name=OnType,proto3,oneof" json:"OnType,omitempty"`
	OnResource *Meta  `protobuf:"bytes,3,opt,name=OnResource,proto3,oneof" json:"OnResource,omitempty"`
	// If exists and set to the true the watcher should be destroyed for the tag in question.
	Delete *bool `protobuf:"varint,4,opt,name=delete,proto3,oneof" json:"delete,omitempty"`
}

func (x *WatcherEventIn) Reset() {
	*x = WatcherEventIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatcherEventIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherEventIn) ProtoMessage() {}

func (x *WatcherEventIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherEventIn.ProtoReflect.Descriptor instead.
func (*WatcherEventIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{11}
}

func (x *WatcherEventIn) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *WatcherEventIn) GetOnType() *Type {
	if x != nil {
		return x.OnType
	}
	return nil
}

func (x *WatcherEventIn) GetOnResource() *Meta {
	if x != nil {
		return x.OnResource
	}
	return nil
}

func (x *WatcherEventIn) GetDelete() bool {
	if x != nil && x.Delete != nil {
		return *x.Delete
	}
	return false
}

type WatcherEventOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag uint64             `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Ref *Meta              `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Op  WatcherEventOut_Op `protobuf:"varint,3,opt,name=op,proto3,enum=wire.WatcherEventOut_Op" json:"op,omitempty"`
}

func (x *WatcherEventOut) Reset() {
	*x = WatcherEventOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatcherEventOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherEventOut) ProtoMessage() {}

func (x *WatcherEventOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherEventOut.ProtoReflect.Descriptor instead.
func (*WatcherEventOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{12}
}

func (x *WatcherEventOut) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *WatcherEventOut) GetRef() *Meta {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *WatcherEventOut) GetOp() WatcherEventOut_Op {
	if x != nil {
		return x.Op
	}
	return WatcherEventOut_Created
}

type ListIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ListIn) Reset() {
	*x = ListIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIn) ProtoMessage() {}

func (x *ListIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIn.ProtoReflect.Descriptor instead.
func (*ListIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{13}
}

func (x *ListIn) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type ListOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref []*Meta `protobuf:"bytes,1,rep,name=ref,proto3" json:"ref,omitempty"`
}

func (x *ListOut) Reset() {
	*x = ListOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOut) ProtoMessage() {}

func (x *ListOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOut.ProtoReflect.Descriptor instead.
func (*ListOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{14}
}

func (x *ListOut) GetRef() []*Meta {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetEventsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref   *Meta      `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Level EventLevel `protobuf:"varint,2,opt,name=level,proto3,enum=wire.EventLevel" json:"level,omitempty"`
}

func (x *GetEventsIn) Reset() {
	*x = GetEventsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsIn) ProtoMessage() {}

func (x *GetEventsIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsIn.ProtoReflect.Descriptor instead.
func (*GetEventsIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{15}
}

func (x *GetEventsIn) GetRef() *Meta {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *GetEventsIn) GetLevel() EventLevel {
	if x != nil {
		return x.Level
	}
	return EventLevel_Error
}

type GetEventsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Exists bool     `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *GetEventsOut) Reset() {
	*x = GetEventsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsOut) ProtoMessage() {}

func (x *GetEventsOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsOut.ProtoReflect.Descriptor instead.
func (*GetEventsOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{16}
}

func (x *GetEventsOut) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsOut) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type DeleteResourceIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref *Meta `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *DeleteResourceIn) Reset() {
	*x = DeleteResourceIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResourceIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceIn) ProtoMessage() {}

func (x *DeleteResourceIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceIn.ProtoReflect.Descriptor instead.
func (*DeleteResourceIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteResourceIn) GetRef() *Meta {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteResourceOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteResourceOut) Reset() {
	*x = DeleteResourceOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResourceOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceOut) ProtoMessage() {}

func (x *DeleteResourceOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceOut.ProtoReflect.Descriptor instead.
func (*DeleteResourceOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResourceOut) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LogIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref   *Meta  `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *LogIn) Reset() {
	*x = LogIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogIn) ProtoMessage() {}

func (x *LogIn) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogIn.ProtoReflect.Descriptor instead.
func (*LogIn) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{19}
}

func (x *LogIn) GetRef() *Meta {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *LogIn) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type LogOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *LogOut) Reset() {
	*x = LogOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOut) ProtoMessage() {}

func (x *LogOut) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_grpc_reswire_resources_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOut.ProtoReflect.Descriptor instead.
func (*LogOut) Descriptor() ([]byte, []int) {
	return file_ipc_grpc_reswire_resources_proto_rawDescGZIP(), []int{20}
}

func (x *LogOut) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_ipc_grpc_reswire_resources_proto protoreflect.FileDescriptor

var file_ipc_grpc_reswire_resources_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x77, 0x69,
	0x72, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x77, 0x69, 0x72, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x12, 0x22, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x22, 0x7b, 0x0a, 0x05, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x77,
	0x68, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x64, 0x22, 0x3a, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x1e, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x05, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x12, 0x22, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x31, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x12, 0x22, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x69,
	0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22,
	0x3e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x4c, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49,
	0x6e, 0x12, 0x22, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29, 0x0a,
	0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4f, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x0e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x27, 0x0a,
	0x06, 0x4f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x06, 0x4f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x0a, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x69, 0x72,
	0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x48, 0x01, 0x52, 0x0a, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x4f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x42,
	0x0d, 0x0a, 0x0b, 0x5f, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x0f, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x1c, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x28, 0x0a,
	0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x77, 0x69, 0x72, 0x65,
	0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74,
	0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x3e, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x03, 0x22, 0x28, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x6e, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x27, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x03,
	0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x69, 0x72, 0x65,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22, 0x53, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22,
	0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x12,
	0x23, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x30, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e,
	0x12, 0x1c, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22, 0x2d,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x48, 0x0a,
	0x05, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x03, 0x72, 0x65, 0x66, 0x12, 0x21, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x4f, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x2a, 0x2a, 0x0a, 0x0a, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x41, 0x6c, 0x6c, 0x10, 0x02, 0x32, 0xe6, 0x03, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x1a, 0x17,
	0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x1a, 0x17, 0x2e, 0x77, 0x69,
	0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0b, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x77, 0x69, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x1a, 0x12, 0x2e, 0x77, 0x69, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x00,
	0x12, 0x3d, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x1a, 0x15, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x11, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x1a,
	0x12, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x0b, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x77, 0x69, 0x72, 0x65,
	0x2e, 0x4c, 0x6f, 0x67, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x1a, 0x15, 0x2e, 0x77, 0x69, 0x72,
	0x65, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x75,
	0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x25, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x0c, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x1a, 0x0d, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x63, 0x68, 0x62, 0x61, 0x63, 0x68, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x67, 0x69, 0x74, 0x2f, 0x70, 0x6c, 0x61, 0x69, 0x64, 0x2f, 0x69, 0x70, 0x63, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x77, 0x69, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ipc_grpc_reswire_resources_proto_rawDescOnce sync.Once
	file_ipc_grpc_reswire_resources_proto_rawDescData = file_ipc_grpc_reswire_resources_proto_rawDesc
)

func file_ipc_grpc_reswire_resources_proto_rawDescGZIP() []byte {
	file_ipc_grpc_reswire_resources_proto_rawDescOnce.Do(func() {
		file_ipc_grpc_reswire_resources_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_grpc_reswire_resources_proto_rawDescData)
	})
	return file_ipc_grpc_reswire_resources_proto_rawDescData
}

var file_ipc_grpc_reswire_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ipc_grpc_reswire_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_ipc_grpc_reswire_resources_proto_goTypes = []interface{}{
	(EventLevel)(0),               // 0: wire.EventLevel
	(WatcherEventOut_Op)(0),       // 1: wire.WatcherEventOut.Op
	(*CreateResourceIn)(nil),      // 2: wire.CreateResourceIn
	(*CreateResourceOut)(nil),     // 3: wire.CreateResourceOut
	(*Event)(nil),                 // 4: wire.Event
	(*Meta)(nil),                  // 5: wire.Meta
	(*Type)(nil),                  // 6: wire.Type
	(*GetIn)(nil),                 // 7: wire.GetIn
	(*GetOut)(nil),                // 8: wire.GetOut
	(*GetStatusIn)(nil),           // 9: wire.GetStatusIn
	(*GetStatusOut)(nil),          // 10: wire.GetStatusOut
	(*UpdateStatusIn)(nil),        // 11: wire.UpdateStatusIn
	(*UpdateStatusOut)(nil),       // 12: wire.UpdateStatusOut
	(*WatcherEventIn)(nil),        // 13: wire.WatcherEventIn
	(*WatcherEventOut)(nil),       // 14: wire.WatcherEventOut
	(*ListIn)(nil),                // 15: wire.ListIn
	(*ListOut)(nil),               // 16: wire.ListOut
	(*GetEventsIn)(nil),           // 17: wire.GetEventsIn
	(*GetEventsOut)(nil),          // 18: wire.GetEventsOut
	(*DeleteResourceIn)(nil),      // 19: wire.DeleteResourceIn
	(*DeleteResourceOut)(nil),     // 20: wire.DeleteResourceOut
	(*LogIn)(nil),                 // 21: wire.LogIn
	(*LogOut)(nil),                // 22: wire.LogOut
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_ipc_grpc_reswire_resources_proto_depIdxs = []int32{
	5,  // 0: wire.CreateResourceIn.target:type_name -> wire.Meta
	23, // 1: wire.Event.when:type_name -> google.protobuf.Timestamp
	0,  // 2: wire.Event.level:type_name -> wire.EventLevel
	6,  // 3: wire.Meta.kind:type_name -> wire.Type
	5,  // 4: wire.GetIn.target:type_name -> wire.Meta
	5,  // 5: wire.GetStatusIn.target:type_name -> wire.Meta
	5,  // 6: wire.UpdateStatusIn.target:type_name -> wire.Meta
	6,  // 7: wire.WatcherEventIn.OnType:type_name -> wire.Type
	5,  // 8: wire.WatcherEventIn.OnResource:type_name -> wire.Meta
	5,  // 9: wire.WatcherEventOut.ref:type_name -> wire.Meta
	1,  // 10: wire.WatcherEventOut.op:type_name -> wire.WatcherEventOut.Op
	6,  // 11: wire.ListIn.type:type_name -> wire.Type
	5,  // 12: wire.ListOut.ref:type_name -> wire.Meta
	5,  // 13: wire.GetEventsIn.ref:type_name -> wire.Meta
	0,  // 14: wire.GetEventsIn.level:type_name -> wire.EventLevel
	4,  // 15: wire.GetEventsOut.events:type_name -> wire.Event
	5,  // 16: wire.DeleteResourceIn.ref:type_name -> wire.Meta
	5,  // 17: wire.LogIn.ref:type_name -> wire.Meta
	4,  // 18: wire.LogIn.event:type_name -> wire.Event
	2,  // 19: wire.ResourceController.Create:input_type -> wire.CreateResourceIn
	19, // 20: wire.ResourceController.Delete:input_type -> wire.DeleteResourceIn
	7,  // 21: wire.ResourceController.Get:input_type -> wire.GetIn
	9,  // 22: wire.ResourceController.GetStatus:input_type -> wire.GetStatusIn
	11, // 23: wire.ResourceController.UpdateStatus:input_type -> wire.UpdateStatusIn
	17, // 24: wire.ResourceController.GetEvents:input_type -> wire.GetEventsIn
	21, // 25: wire.ResourceController.Log:input_type -> wire.LogIn
	13, // 26: wire.ResourceController.Watcher:input_type -> wire.WatcherEventIn
	15, // 27: wire.ResourceController.List:input_type -> wire.ListIn
	3,  // 28: wire.ResourceController.Create:output_type -> wire.CreateResourceOut
	20, // 29: wire.ResourceController.Delete:output_type -> wire.DeleteResourceOut
	8,  // 30: wire.ResourceController.Get:output_type -> wire.GetOut
	10, // 31: wire.ResourceController.GetStatus:output_type -> wire.GetStatusOut
	12, // 32: wire.ResourceController.UpdateStatus:output_type -> wire.UpdateStatusOut
	18, // 33: wire.ResourceController.GetEvents:output_type -> wire.GetEventsOut
	22, // 34: wire.ResourceController.Log:output_type -> wire.LogOut
	14, // 35: wire.ResourceController.Watcher:output_type -> wire.WatcherEventOut
	16, // 36: wire.ResourceController.List:output_type -> wire.ListOut
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_ipc_grpc_reswire_resources_proto_init() }
func file_ipc_grpc_reswire_resources_proto_init() {
	if File_ipc_grpc_reswire_resources_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipc_grpc_reswire_resources_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatcherEventIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatcherEventOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResourceIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResourceOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_grpc_reswire_resources_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ipc_grpc_reswire_resources_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_grpc_reswire_resources_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipc_grpc_reswire_resources_proto_goTypes,
		DependencyIndexes: file_ipc_grpc_reswire_resources_proto_depIdxs,
		EnumInfos:         file_ipc_grpc_reswire_resources_proto_enumTypes,
		MessageInfos:      file_ipc_grpc_reswire_resources_proto_msgTypes,
	}.Build()
	File_ipc_grpc_reswire_resources_proto = out.File
	file_ipc_grpc_reswire_resources_proto_rawDesc = nil
	file_ipc_grpc_reswire_resources_proto_goTypes = nil
	file_ipc_grpc_reswire_resources_proto_depIdxs = nil
}
